baseURL: 'https://curriculum-academigo.vercel.app/'
languageCode: 'es-es'
title: 'Jorge Luis Ayona Inglis - CV'
theme: 'papermod'

defaultContentLanguage: es
hasCJKLanguage: false
removePathAccents: true

params:
  author: Jorge Luis Ayona Inglis
  description: "Teología | Filosofía | Consultoría | Formación Humana"
  defaultTheme: auto
  ShowReadingTime: false
  ShowShareButtons: false
